import React, { useState, useRef, useEffect } from "react";
import AllLogs from "./AllLogs";
import ScheduleLogs from "./ScheduleLogs";
import Others from "./Others";
import { FiDownload } from "react-icons/fi";
import HelpInfo from "../../../../components/HelpInfo";

export default function Logs() {
  const [activeTab, setActiveTab] = useState("all");
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const dropdownRef = useRef(null);

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
        setDropdownOpen(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const renderTab = () => {
    switch (activeTab) {
      case "all":
        return <AllLogs />;
      case "schedule":
        return <ScheduleLogs />;
      case "others":
        return <Others />;
      default:
        return null;
    }
  };

  return (
    <div className="p-0 ">
      {/* Breadcrumbs */}
      <div className="text-gray-500 text-sm mb-2 flex items-center gap-1">
        <button onClick={() => setActiveTab("all")} className="hover:underline">
          Logs
        </button>
        <span>&gt;</span>
        <span>
          {activeTab === "all" && "All Logs"}
          {activeTab === "schedule" && "Schedule Logs"}
          {activeTab === "others" && "Others"}
        </span>
      </div>
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-2xl font-bold">Logs</h2>

        <HelpInfo
          title="Admin Logs Help"
          description={`Page Description: Audit every message or notice sent from the admin panel. Switch between all logs, scheduled logs, and other automation logs for deeper troubleshooting.


7.1 Page Overview

View communication history and scheduled batches to ensure everything was sent properly.

Sections:
- Breadcrumb & Header: Display the current log subset
- Tab Bar: Buttons for All Logs, Schedule Logs, and Others
- Export Controls: Download icon/button to export filtered logs


7.2 All Logs Tab

Chronological timeline of all dispatched communications.

Sections:
- Log Table: Columns for title, recipient count, channel(s), and timestamp
- Filters: Search/date filters (inside AllLogs component) to narrow the data
- Channel Chips: Colored badges for SMS, Email, App push
- Detail Drawer: Click a row to inspect full payload or delivery info


7.3 Schedule Logs Tab

Monitor jobs that are scheduled or recently executed.

Sections:
- Job List: Shows job name, scheduled time, target audience, and status (Queued, Sent, Failed)
- Action Buttons: Pause, resume, or cancel future jobs
- Execution History: Notes when the job actually ran and success metrics


7.4 Others Tab

Review automation-specific logs, import summaries, or integration events.

Sections:
- Automation Logs: Items generated by workflows, triggers, or third-party connectors
- Failure Reports: Highlights entries that require admin attention
- Import History: Tracks bulk upload operations with results
- Export Tools: Download raw JSON/CSV for advanced analysis`}
        />
      </div>

      {/* Tabs */}
      <div className="flex gap-4 border-b border-gray-300">
        {["all", "schedule", "others"].map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`relative capitalize pb-2 ${
              activeTab === tab
                ? "text-blue-600 font-semibold"
                : "text-gray-500"
            }`}
          >
            {tab === "all"
              ? "All Logs"
              : tab === "schedule"
              ? "Schedule Logs"
              : "Others"}
            {activeTab === tab && (
              <span className="absolute left-0 right-0 -bottom-[1px] h-0.5 bg-blue-600"></span>
            )}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="mt-4">{renderTab()}</div>
    </div>
  );
}
